import time
import random

def get_pickup_lines():
    return [
        "Are you a magician? Because whenever I look at you, everyone else disappears.",
        "Do you have a name, or can I call you mine?",
        "Do you have a map? I keep getting lost in your eyes.",
        "Is your name Google? Because you've got everything I've been searching for.",
        "Are you French? Because Eiffel for you.",
        "If you were a vegetable, you'd be a cute-cumber.",
        "Do you have a Band-Aid? I just scraped my knee falling for you.",
        "Is your name Wi-Fi? Because I'm feeling a connection.",
        "You must be made of copper and tellurium because you're Cu-Te.",
        "Are you a parking ticket? Because you've got FINE written all over you.",
        "Is your name Chapstick? Because you're da balm!",
        "Are you Australian? Because when I look at you, I feel like I’m down under.",
        "If beauty were time, you'd be an eternity.",
        "Do you believe in love at first sight, or should I walk by again?",
        "Are you a loan from a bank? Because you have my interest.",
        "Are you made of lava? Because you’re hot!",
        "Is your name Google? Because you’ve got everything I’ve been searching for.",
        "Do you have a sunburn, or are you always this hot?",
        "Are you a time traveler? Because I see you in my future.",
        "If you were a fruit, you’d be a fineapple.",
        "Is your dad a baker? Because you're a cutie pie!",
        "Do you have a pencil? Cause I want to erase your past and write our future.",
        "Are you a camera? Every time I look at you, I smile.",
        "Are you an alien? Because you just abducted my heart.",
        "If you were a cat, you’d purr-fect.",
        "Is your name Starbucks? Because I like you a latte.",
        "Are you a snowstorm? Because you make my heart race.",
        "Do you have a quarter? Because I want to call my mom and tell her I met 'The One.'",
        "Are you a magician? Because your beauty is making me spellbound.",
        "Are you a time traveler? Because I can see you in my future.",
        "Is your name Google? Because you’ve got everything I’ve been searching for.",
        "Do you have a map? Because I just got lost in your eyes.",
        "Is your dad a scientist? Because you're making my heart race.",
        "Are you an angel? Because I've been looking for you my whole life.",
        "Are you a campfire? Because you’re hot and I want s'more.",
        "If looks could kill, you'd be a heartbreaker.",
        "If I could rearrange the alphabet, I’d put U and I together.",
        "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
        "Are you a star? Because your beauty lights up the night.",
        "Are you a flower? Because you’re blooming beautiful.",
        "Is your name Wi-Fi? Because I’m feeling a connection.",
        "Do you have a map? I keep getting lost in your eyes.",
        "Are you a beaver? Because daaaaam.",
        "If you were a vegetable, you’d be a cute-cumber.",
        "Is your name Google? Because you have everything I’ve been searching for.",
        "Do you have a mirror in your pocket? Because I can see myself in your pants.",
        "Are you a campfire? Because you’re hot and I want s’more.",
        "Are you an alien? Because you just abducted my heart.",
        "Do you believe in love at first sight, or should I walk by again?",
        "Is your name Chapstick? Because you’re da balm!",
        "Are you a time traveler? Because I see you in my future.",
        "If beauty were time, you’d be an eternity.",
        "If you were a fruit, you’d be a fineapple.",
        "Do you have a name, or can I call you mine?",
        "Are you a loan from a bank? Because you have my interest.",
        "Are you made of copper and tellurium? Because you’re Cu-Te.",
        "If you were a vegetable, you’d be a cute-cumber.",
        "Is your name Wi-Fi? Because I’m feeling a connection.",
        "Are you a parking ticket? Because you’ve got FINE written all over you.",
        "Are you a gaming console? Because you've got all the right moves.",
        "Is your name Zelda? Because you're a treasure.",
        "Are you a loot box? Because I feel lucky every time I see you.",
        "Do you play League of Legends? Because you've got me spellbound.",
        "Are you a cheat code? Because you just made my day amazing.",
        "Do you have a name, or can I call you mine in my game?",
        "Are you a high score? Because I keep trying to beat it.",
        "Are you a boss level? Because you’ve got me completely challenged.",
        "Do you have a joystick? Because you've got me spinning.",
        "Are you a quest item? Because I’ve been searching for you.",
        "Are you a power-up? Because you just made my day a whole lot better.",
        "Do you play Minecraft? Because you just built a castle in my heart.",
        "Are you a rare item drop? Because finding you was luckiest thing ever.",
        "Is your name Mario? Because you’ve got me jumping for joy.",
        "Are you a pixel? Because you’re a part of my perfect picture.",
        "Do you know any RPGs? Because you’ve got me on a quest for your heart.",
        "Are you a side quest? Because I’m getting lost in you.",
        "Are you a game developer? Because you just created a new level of awesome.",
        "Is your name Sonic? Because you’ve got me running after you.",
        "Do you play any games? Because you've got me hooked.",
        "Are you a health potion? Because you make me feel better.",
        "Are you a character from Overwatch? Because you're a true hero.",
        "Is your name Lara Croft? Because you've got me exploring new territories.",
        "Do you have a favorite game? Because I’d love to play it with you.",
        "Are you a victory royale? Because you’re my top choice.",
        "Do you play Fortnite? Because you're the treasure I was looking for.",
        "Are you a new DLC? Because you just expanded my heart.",
        "Do you play any games? Because you’re my ultimate prize.",
        "Are you a cheat code? Because you’re making my life perfect."
    ]

def get_random_pickup_line():
    pickup_lines = get_pickup_lines()  # Call the function to get the list of lines
    return random.choice(pickup_lines)  # Select a random line

print(get_random_pickup_line())
time.sleep(99)  # Wait for 99 seconds
